version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - XDG_RUNTIME_DIR=/tmp/runtime-$USER
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: "./CalibrationSoft"

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: "./CalibrationSoftTests"
